# Mid-Semester Exam

This mid-semester exam contains practical pandas tasks using the provided datasets (`jamesbond.csv` and `google_stock_price.csv`).

Instructions for students:
- Implement the required functions in this notebook.
- Each question is followed by instructor solution and a small assertion test for reference and validation.
- Do not modify the assertion cells; they are used to validate correctness during grading.

Notes:
- The top setup cell imports necessary libraries (importing libraries is not a numbered question).
- Each numbered question below contains a single function implementing the instructor solution and a small set of assertions verifying expected behaviour.

In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
name = 'Johann Karl'
roll_number = '2423382'

---
## QUESTIONS
---

### 1. Loading James Bond Dataset

Return: A pandas DataFrame loaded from the CSV path or file-like object.

Load the file `jamesbond.csv` into a DataFrame named `bond`.

In [13]:
def load_bond(path_or_buffer: str='data/sba_questions/jamesbond.csv') -> pd.DataFrame:
    bond = pd.read_csv(path_or_buffer)
    return bond
load_bond('jamesbond.csv')

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

### 2. Loading Google Stock Dataset

Return: A pandas DataFrame loaded from the CSV path or file-like object.

Load the file `google_stock_price.csv` into a DataFrame named `google`.

In [21]:
def load_google(path_or_buffer: str='data/sba_questions/google_stock_price.csv') -> pd.DataFrame:
    google = pd.read_csv(path_or_buffer)
    return google
google= load_google('google_stock_price.csv')
google

            Date       Price
0     2004-08-19    2.490664
1     2004-08-20    2.515820
2     2004-08-23    2.758411
3     2004-08-24    2.770615
4     2004-08-25    2.614201
...          ...         ...
4788  2023-08-28  132.080002
4789  2023-08-29  132.998001
4790  2023-08-30  135.570007
4791  2023-08-31  137.050003
4792  2023-09-01  138.429993

[4793 rows x 2 columns]

### 3. Viewing Data – James Bond Dataset

Return: A DataFrame containing the first five rows of the provided `bond` DataFrame.

Display the first five rows of the `bond` DataFrame.

In [16]:
def bond_head(df: pd.DataFrame) -> pd.DataFrame:
    return df.head()
bond_head(bond)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

### 4. Viewing Data – Google Stock Dataset

Return: A DataFrame containing the first five rows of the provided `google` DataFrame.

Display the first five rows of the `google` DataFrame.

In [22]:
def google_head(df: pd.DataFrame) -> pd.DataFrame:
    return df.head()
google_head(google)

         Date     Price
0  2004-08-19  2.490664
1  2004-08-20  2.515820
2  2004-08-23  2.758411
3  2004-08-24  2.770615
4  2004-08-25  2.614201

### 5. Column Names – James Bond Dataset

Return: A list of column names for the `bond` DataFrame.

Display the column names of the `bond` DataFrame.

In [23]:
def bond_columns(df: pd.DataFrame) -> list:
    return df.columns
bond_columns(bond)

Index(['Film', 'Year', 'Actor', 'Director', 'Box Office', 'Budget',
       'Bond Actor Salary'],
      dtype='object')

### 6. Column Names – Google Stock Dataset

Return: A list of column names for the `google` DataFrame.

Display the column names of the `google` DataFrame.

In [24]:
def google_columns(df: pd.DataFrame) -> list:
    return df.columns
google_columns(google)

Index(['Date', 'Price'], dtype='object')

### 7. Dataset Shape – James Bond Dataset

Return: A tuple (number of rows, number of columns) for the `bond` DataFrame.

Display the number of rows and columns in the `bond` DataFrame.

In [26]:
def bond_shape(df: pd.DataFrame) -> tuple:
    return df.shape
bond_shape(bond)

(27, 7)

### 8. Dataset Shape – Google Stock Dataset

Return: A tuple (number of rows, number of columns) for the `google` DataFrame.

Display the number of rows and columns in the `google` DataFrame.

In [27]:
def google_shape(df: pd.DataFrame) -> tuple:
    return df.shape
google_shape(google)

(4793, 2)

### 9. Rename Column – James Bond Dataset

Return: A DataFrame with column `Bond Actor Salary` renamed to `Bond_Salary`.

Rename the column `Bond Actor Salary` to `Bond_Salary` in the `bond` DataFrame.

In [37]:
def rename_bond_salary(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename({"Bond Actor Salary":"Bond Salary"})
rename_bond_salary(bond)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

### 10. Data Type Conversion – James Bond Dataset

Return: A DataFrame where the `Bond_Salary` column is of numeric dtype (non-convertible values coerced to NaN).

Convert the `Bond_Salary` column to numeric using `errors='coerce'`.

In [44]:
def convert_bond_salary_to_numeric(df: pd.DataFrame) -> pd.DataFrame:
    df["Bond Actor Salary"]= pd.to_numeric(df["Bond Actor Salary"],errors="coerce")
    return df
convert_bond_salary_to_numeric(bond)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

### 11. Handling Missing Values – James Bond Dataset

Return: A DataFrame where missing values in `Bond_Salary` are replaced by 0.

Replace all missing values in `Bond_Salary` with `0`.

In [41]:
def fill_bond_salary_zero(df: pd.DataFrame) -> pd.DataFrame:
    df["Bond Actor Salary"].fillna("0")
    return df
fill_bond_salary_zero(bond)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

### 12. Date Conversion – Google Stock Dataset

Return: A DataFrame where `Date` has been converted to pandas datetime dtype.

Convert the `Date` column in the `google` DataFrame to datetime format.

In [47]:
def convert_google_date(df: pd.DataFrame) -> pd.DataFrame:
    df["Date"]= pd.to_datetime(["Date"])
    return df
convert_google_date(google)

DateParseError: Unknown datetime string format, unable to parse: Date, at position 0

### 13. Setting Index – Google Stock Dataset

Return: A DataFrame with `Date` set as the index.

Set the `Date` column as the index of the `google` DataFrame.

In [27]:
def set_google_index_date(df: pd.DataFrame) -> pd.DataFrame:

### 14. Display After Indexing – Google Stock Dataset

Return: The first five rows of the `google` DataFrame after setting index.

Display the first five rows of the `google` DataFrame after setting the index.

In [29]:
def google_head_indexed(df: pd.DataFrame) -> pd.DataFrame:
    pass

### 15. Filtering Data – Google Stock Dataset

Return: DataFrame containing rows where `Price` is greater than the average `Price`.

Display all rows from the `google` DataFrame where the `Price` is greater than the average `Price`.

In [46]:
def filter_price_above_average(df: pd.DataFrame) -> pd.DataFrame:
    return df[(df['Price']>df['Price'].mean())]

filter_price_above_average(google)

            Date       Price
3067  2016-10-24   40.244999
3068  2016-10-25   40.834000
3069  2016-10-26   40.317001
3071  2016-10-28   40.417500
3119  2017-01-09   40.320000
...          ...         ...
4788  2023-08-28  132.080002
4789  2023-08-29  132.998001
4790  2023-08-30  135.570007
4791  2023-08-31  137.050003
4792  2023-09-01  138.429993

[1672 rows x 2 columns]

### 16. Grouping Data – James Bond Dataset

Return: A Series mapping each actor to the number of films they performed in the dataset.

Display the number of films performed by each actor using the `bond` DataFrame.

In [51]:
def films_per_actor(df: pd.DataFrame, actor_col: str='Actor') -> pd.Series:
    return df.groupby('Actor').count()
films_per_actor(bond)

                Film  Year  Director  Box Office  Budget  Bond Actor Salary
Actor
Daniel Craig       5     5         5           5       5                  5
David Niven        1     1         1           1       1                  0
George Lazenby     1     1         1           1       1                  1
Pierce Brosnan     4     4         4           4       4                  4
Roger Moore        7     7         7           7       7                  2
Sean Connery       7     7         7           7       7                  6
Timothy Dalton     2     2         2           2       2                  2